### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by CircuitCM** [ddelange/pipgrip#116]
Hi,

Am I doing something wrong?

pipgrip --tree requests -vvv

```DEBUG: environment: {'implementation_name': 'cpython', 'implementation_version': '3.10.12', 'os_name': 'nt', 'platform_machine': 'AMD64', 'platform_release': '10', 'platform_system': 'Windows', 'platform_version': '10.0.22621', 'python_full_version': '3.10.12', 'platform_python_implementation': 'CPython', 'python_version': '3.10', 'sys_platform': 'win32'}
DEBUG: pip version: [23, 2, 1]
DEBUG: pipgrip version: 0.10.6
INFO: fact: _root_ is root
INFO: derived: root
DEBUG: unsatisfied: [<Term root>]
INFO: fact: root depends on requests (*)
INFO: selecting _root_ (0.0.0)
INFO: derived: requests (*)
DEBUG: unsatisfied: [<Term requests (*)>]
INFO: discovering requests
DEBUG: Getting report for requests (with fallback cache_dir ~\AppData\Local\pip\cache\wheels\pipgrip)
DEBUG: ['~\\mambaforge\\envs\\AIPlayground310\\python.exe', '-m', 'pip', 'install', '-qq', '--no-deps', '--ignore-installed', '--disable-pip-version-check', '--dry-run', '--no-deps', '--cache-dir', '~\AppData\\Local\\pip\\cache\\wheels\\pipgrip', '--report', '-', 'requests']```
`Traceback (most recent call last):
  File "~\mambaforge\envs\AIPlayground310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "~\mambaforge\envs\AIPlayground310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "~\mambaforge\envs\AIPlayground310\Scripts\pipgrip.exe\__main__.py", line 7, in <module>
  File "~\mambaforge\envs\AIPlayground310\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "~\mambaforge\envs\AIPlayground310\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "~\mambaforge\envs\AIPlayground310\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "~\mambaforge\envs\AIPlayground310\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "~\mambaforge\envs\AIPlayground310\lib\site-packages\pipgrip\cli.py", line 440, in main
    solution = solver.solve()
  File "~\mambaforge\envs\AIPlayground310\lib\site-packages\pipgrip\libs\mixology\version_solver.py", line 74, in solve
    if not self._run():
  File "~\mambaforge\envs\AIPlayground310\lib\site-packages\pipgrip\libs\mixology\version_solver.py", line 90, in _run
    next_package = self._choose_package_version()
  File "~\mambaforge\envs\AIPlayground310\lib\site-packages\pipgrip\libs\mixology\version_solver.py", line 363, in _choose_package_version
    versions = self._source.versions_for(term.package, term.constraint.constraint)
  File "~\mambaforge\envs\AIPlayground310\lib\site-packages\pipgrip\libs\mixology\package_source.py", line 77, in versions_for
    return self._versions_for(package, constraint)
  File "~\mambaforge\envs\AIPlayground310\lib\site-packages\pipgrip\package_source.py", line 185, in _versions_for
    self.discover_and_add(package.req.__str__())
  File "~\mambaforge\envs\AIPlayground310\lib\site-packages\pipgrip\package_source.py", line 146, in discover_and_add
    to_create = discover_dependencies_and_versions(
  File "~\mambaforge\envs\AIPlayground310\lib\site-packages\pipgrip\pipper.py", line 478, in discover_dependencies_and_versions
    report = _get_package_report(
  File "~\mambaforge\envs\AIPlayground310\lib\site-packages\pipgrip\pipper.py", line 297, in _get_package_report
    out = stream_bash_command(args)
  File "~\mambaforge\envs\AIPlayground310\lib\site-packages\pipgrip\pipper.py", line 95, in stream_bash_command
    out += check_io()
  File "~\mambaforge\envs\AIPlayground310\lib\site-packages\pipgrip\pipper.py", line 83, in check_io
    line = process.stdout.readline().decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 494: invalid start byte

**Comment by ddelange** [comment]
Hi @CircuitCM 👋 

Thanks for the report! Fix incoming
