### ISSUE TITLE
--reversed-tree raises NotImplementedError

### ISSUE THREAD

**Issue by tekumara** [ddelange/pipgrip#134]
#### What you were trying to do (and why)

`--reversed-tree` raises NotImplementedError

#### What happened (including command output)

<details><summary>Command output</summary><p>

```console
$ pipgrip -vvv --reversed-tree
....

Traceback (most recent call last):
  File "/Users/tekumara/.local/bin/pipgrip", line 8, in <module>
    sys.exit(main())
  File "/Users/tekumara/.local/pipx/venvs/pipgrip/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/tekumara/.local/pipx/venvs/pipgrip/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/tekumara/.local/pipx/venvs/pipgrip/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/tekumara/.local/pipx/venvs/pipgrip/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/tekumara/.local/pipx/venvs/pipgrip/lib/python3.10/site-packages/pipgrip/cli.py", line 509, in main
    raise NotImplementedError()
NotImplementedError
<output here>
```

</p></details>

#### What you expected to happen

A tree with leaf nodes that are dependents rather than dependencies

**Comment by ddelange** [comment]
Hi @tekumara :wave: indeed, I never found a nice implementation for `reverse_tree`. There's now only `pipgrip.cli.build_tree`. The flag is there since the beginning (because pipdeptree had it, I wanted it too :sweat_smile:).
