### ISSUE TITLE
Are environment markers aka conditional requirements supported?

### ISSUE THREAD

**Issue by davidxia** [ddelange/pipgrip#71]
#### Description

My `requirements.txt` file has this line.

```
fastavro==0.21.24; python_version < '3.8'
```

I'm in a py38 environment using latest pipgrip 0.6.12. When I run `pipgrip -vv --tree -r requirements.txt`, I get the error

```
INFO: discovering fastavro==0.21.24; python_version < "3.8"
ERROR: Failed to extract wheel filename from pip stdout:
Looking in indexes: https://artifactory.spotify.net/artifactory/api/pypi/pypi/simple/
Ignoring fastavro: markers 'python_version < "3.8"' don't match your environment
Traceback (most recent call last):
  File "/Users/dxia/src/ghe.spotify.net/kubeflow-platform/spotify-kubeflow/.tox/reqs-dryrun/bin/pipgrip", line 8, in <module>
    sys.exit(main())
  File "/Users/dxia/src/ghe.spotify.net/kubeflow-platform/spotify-kubeflow/.tox/reqs-dryrun/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/dxia/src/ghe.spotify.net/kubeflow-platform/spotify-kubeflow/.tox/reqs-dryrun/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/dxia/src/ghe.spotify.net/kubeflow-platform/spotify-kubeflow/.tox/reqs-dryrun/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/dxia/src/ghe.spotify.net/kubeflow-platform/spotify-kubeflow/.tox/reqs-dryrun/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/dxia/src/ghe.spotify.net/kubeflow-platform/spotify-kubeflow/.tox/reqs-dryrun/lib/python3.8/site-packages/pipgrip/cli.py", line 420, in main
    source.root_dep(root_dependency)
  File "/Users/dxia/src/ghe.spotify.net/kubeflow-platform/spotify-kubeflow/.tox/reqs-dryrun/lib/python3.8/site-packages/pipgrip/package_source.py", line 154, in root_dep
    self.discover_and_add(req.__str__())
  File "/Users/dxia/src/ghe.spotify.net/kubeflow-platform/spotify-kubeflow/.tox/reqs-dryrun/lib/python3.8/site-packages/pipgrip/package_source.py", line 129, in discover_and_add
    to_create = discover_dependencies_and_versions(
  File "/Users/dxia/src/ghe.spotify.net/kubeflow-platform/spotify-kubeflow/.tox/reqs-dryrun/lib/python3.8/site-packages/pipgrip/pipper.py", line 407, in discover_dependencies_and_versions
    wheel_fname = _download_wheel(
  File "/Users/dxia/src/ghe.spotify.net/kubeflow-platform/spotify-kubeflow/.tox/reqs-dryrun/lib/python3.8/site-packages/pipgrip/pipper.py", line 342, in _download_wheel
    raise RuntimeError("Failed to download/build wheel for {}".format(package))
RuntimeError: Failed to download/build wheel for fastavro==0.21.24; python_version < "3.8"
```

Output has `Ignoring fastavro: markers 'python_version < "3.8"' don't match your environment` but then tries to download the wheel. I expect pipgrip to completely ignore fastavro in this environment.

#### Use case / motivation / context

Pipgrip should support pip environment markers for a more accurate result.

**Comment by ddelange** [comment]
Thanks for the report! Environment markers were only evaluated for nested dependencies until now.

Released [`0.6.13`](https://github.com/ddelange/pipgrip/releases/tag/0.6.13)
