### ISSUE TITLE
Skip package versions when wheel fails to build

### ISSUE THREAD

**Issue by pmrowla** [ddelange/pipgrip#77]
#### Description

Currently, when testing multiple versions of a package to find a version that satisfies some dependency constraints, if a single wheel for that package fails to build, it causes pipgrip to exit with a `RuntimeError`, even if there are more versions left to test. It would be preferable in some situations to just skip or ignore the version which fails to build, and continue trying the remaining versions of the package.

#### Use case / motivation

In [DVC](https://github.com/iterative/dvc) we have a dependency on `knack` and `oss2`. `knack` requires any `jmespath`, and `oss2` requires `aliyun-python-sdk-core-v3`, which in turn requires `jmespath<1.0.0`.

The problem is that `aliyun-python-sdk-core-v3==2.13.31` on pypi is broken, wheel builds for that version fail due to metadata issue:

```shell
$ python -m pip wheel --no-deps --disable-pip-version-check --wheel-dir /tmp/test-pipgrip aliyun-python-sdk-core-v3==2.13.31
Collecting aliyun-python-sdk-core-v3==2.13.31
  Using cached aliyun-python-sdk-core-v3-2.13.31.tar.gz (440 kB)
  Preparing metadata (setup.py) ... done
  WARNING: Generating metadata for package aliyun-python-sdk-core-v3 produced metadata for project name aliyun-python-sdk-core. Fix your #egg=aliyun-python-sdk-core-v3 fragments.
Discarding https://files.pythonhosted.org/packages/13/63/52c2fc00ce2334cef2051548215ae27878b187b819f01876539608752837/aliyun-python-sdk-core-v3-2.13.31.tar.gz#sha256=427f27f420d3d88577788f703e2ee1b2f804e9ce645a2e175dafe9c56d339b3c (from https://pypi.org/simple/aliyun-python-sdk-core-v3/): Requested aliyun-python-sdk-core from https://files.pythonhosted.org/packages/13/63/52c2fc00ce2334cef2051548215ae27878b187b819f01876539608752837/aliyun-python-sdk-core-v3-2.13.31.tar.gz#sha256=427f27f420d3d88577788f703e2ee1b2f804e9ce645a2e175dafe9c56d339b3c has inconsistent name: filename has 'aliyun-python-sdk-core-v3', but metadata has 'aliyun-python-sdk-core'
ERROR: Could not find a version that satisfies the requirement aliyun-python-sdk-core-v3==2.13.31 (from versions: 2.3.2, 2.3.3, 2.3.4, 2.3.5, 2.3.6, 2.3.7, 2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.4.4, 2.5.0, 2.5.1, 2.5.2, 2.5.3, 2.5.4, 2.5.5, 2.7.2, 2.8.2, 2.8.3, 2.8.4, 2.8.5, 2.8.6, 2.8.7, 2.8.8, 2.8.9, 2.9.0, 2.9.1, 2.9.3, 2.9.4, 2.10.1, 2.11.0, 2.11.1, 2.11.4, 2.11.5, 2.12.1, 2.13.0, 2.13.3, 2.13.8, 2.13.9, 2.13.10, 2.13.11, 2.13.31, 2.13.32, 2.13.33)
ERROR: No matching distribution found for aliyun-python-sdk-core-v3==2.13.31
```

This is fixed in subsequent package versions, but for whatever reason the aliyun maintainers did not remove the 2.13.31 release from pypi.

In pipgrip, this build failure causes pipgrip to exit when trying to find a compatible match between `jmespath` and `aliyun-python-sdk-core-v3`:

```shell
$ pipgrip jmespath aliyun-python-sdk-core-v3 -vv
INFO: discovering jmespath
INFO: discovering aliyun-python-sdk-core-v3
INFO: fact: _root_ is root
INFO: derived: root
INFO: fact: root depends on jmespath (*)
INFO: fact: root depends on aliyun-python-sdk-core-v3 (*)
INFO: selecting _root_ (0.0.0)
INFO: derived: aliyun-python-sdk-core-v3 (*)
INFO: derived: jmespath (*)
INFO: selecting jmespath (1.0.0)
INFO: fact: aliyun-python-sdk-core-v3 (2.13.33) depends on cryptography (>=2.6.0)
INFO: fact: aliyun-python-sdk-core-v3 (2.13.33) depends on jmespath (<1.0.0,>=0.9.3)
INFO: derived: not aliyun-python-sdk-core-v3 (2.13.33)
INFO: discovering aliyun-python-sdk-core-v3==2.13.32
INFO: fact: aliyun-python-sdk-core-v3 (2.13.32) depends on cryptography (>=2.6.0)
INFO: fact: aliyun-python-sdk-core-v3 (2.13.32) depends on jmespath (<1.0.0,>=0.9.3)
INFO: derived: not aliyun-python-sdk-core-v3 (2.13.32)
INFO: discovering aliyun-python-sdk-core-v3==2.13.31
ERROR: Downloading/building wheel for aliyun-python-sdk-core-v3==2.13.31 failed with output:
Collecting aliyun-python-sdk-core-v3==2.13.31
  Using cached aliyun-python-sdk-core-v3-2.13.31.tar.gz (440 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  WARNING: Generating metadata for package aliyun-python-sdk-core-v3 produced metadata for project name aliyun-python-sdk-core. Fix your #egg=aliyun-python-sdk-core-v3 fragments.
...
ERROR: Could not find a version that satisfies the requirement aliyun-python-sdk-core-v3==2.13.31 (from versions: 2.3.2, 2.3.3, 2.3.4, 2.3.5, 2.3.6, 2.3.7, 2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.4.4, 2.5.0, 2.5.1, 2.5.2, 2.5.3, 2.5.4, 2.5.5, 2.7.2, 2.8.2, 2.8.3, 2.8.4, 2.8.5, 2.8.6, 2.8.7, 2.8.8, 2.8.9, 2.9.0, 2.9.1, 2.9.3, 2.9.4, 2.10.1, 2.11.0, 2.11.1, 2.11.4, 2.11.5, 2.12.1, 2.13.0, 2.13.3, 2.13.8, 2.13.9, 2.13.10, 2.13.11, 2.13.31, 2.13.32, 2.13.33)
ERROR: No matching distribution found for aliyun-python-sdk-core-v3==2.13.31
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/pipgrip/0.7.2/libexec/lib/python3.10/site-packages/pipgrip/pipper.py", line 258, in _download_wheel
    out = stream_bash_command(args)
  File "/opt/homebrew/Cellar/pipgrip/0.7.2/libexec/lib/python3.10/site-packages/pipgrip/pipper.py", line 91, in stream_bash_command
    raise subprocess.CalledProcessError(return_code, bash_command, output=out)
subprocess.CalledProcessError: Command '['/opt/homebrew/Cellar/pipgrip/0.7.2/libexec/bin/python3.10', '-m', 'pip', 'wheel', '--no-deps', '--disable-pip-version-check', '--wheel-dir', '/Users/pmrowla/Library/Caches/pip/wheels/pipgrip', '--progress-bar=off', 'aliyun-python-sdk-core-v3==2.13.31']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/bin/pipgrip", line 33, in <module>
    sys.exit(load_entry_point('pipgrip==0.7.2', 'console_scripts', 'pipgrip')())
...
  File "/opt/homebrew/Cellar/pipgrip/0.7.2/libexec/lib/python3.10/site-packages/pipgrip/pipper.py", line 414, in discover_dependencies_and_versions
    wheel_fname = _download_wheel(
  File "/opt/homebrew/Cellar/pipgrip/0.7.2/libexec/lib/python3.10/site-packages/pipgrip/pipper.py", line 266, in _download_wheel
    raise RuntimeError("Failed to download/build wheel for {}".format(package))
RuntimeError: Failed to download/build wheel for aliyun-python-sdk-core-v3==2.13.31
```

If you manually exclude the offending version, pipgrip successfully iterates over the available `aliyun-python-sdk-core-v3` releases and eventually finds a version that succeeds:

```shell
$ pipgrip jmespath "aliyun-python-sdk-core-v3!=2.13.31" -vv
INFO: discovering jmespath
INFO: discovering aliyun-python-sdk-core-v3!=2.13.31
INFO: fact: _root_ is root
INFO: derived: root
INFO: fact: root depends on jmespath (*)
INFO: fact: root depends on aliyun-python-sdk-core-v3 (<2.13.31 || >2.13.31)
INFO: selecting _root_ (0.0.0)
INFO: derived: aliyun-python-sdk-core-v3 (<2.13.31 || >2.13.31)
INFO: derived: jmespath (*)
INFO: selecting jmespath (1.0.0)
INFO: fact: aliyun-python-sdk-core-v3 (2.13.33) depends on cryptography (>=2.6.0)
INFO: fact: aliyun-python-sdk-core-v3 (2.13.33) depends on jmespath (>=0.9.3,<1.0.0)
INFO: derived: not aliyun-python-sdk-core-v3 (2.13.33)
INFO: discovering aliyun-python-sdk-core-v3==2.13.32
INFO: fact: aliyun-python-sdk-core-v3 (2.13.32) depends on cryptography (>=2.6.0)
INFO: fact: aliyun-python-sdk-core-v3 (2.13.32) depends on jmespath (>=0.9.3,<1.0.0)
INFO: derived: not aliyun-python-sdk-core-v3 (2.13.32)
INFO: discovering aliyun-python-sdk-core-v3==2.13.11
INFO: fact: aliyun-python-sdk-core-v3 (2.13.11) depends on jmespath (>=0.9.3,<1.0.0)
INFO: fact: aliyun-python-sdk-core-v3 (2.13.11) depends on pycryptodome (>=3.4.7)
INFO: derived: not aliyun-python-sdk-core-v3 (2.13.11)
INFO: discovering aliyun-python-sdk-core-v3==2.13.10
...
INFO: discovering aliyun-python-sdk-core-v3==2.11.5
INFO: fact: aliyun-python-sdk-core-v3 (2.11.5) depends on pycryptodome (>=3.4.7)
INFO: selecting aliyun-python-sdk-core-v3 (2.11.5)
INFO: derived: pycryptodome (>=3.4.7)
INFO: discovering pycryptodome>=3.4.7
INFO: selecting pycryptodome (3.14.1)
INFO: Version solving took 3.027 seconds.
INFO: Tried 1 solutions.
jmespath==1.0.0
aliyun-python-sdk-core-v3==2.11.5
pycryptodome==3.14.1
```

The end result is that in DVC, we cannot use any of homebrew's utilities for auto-updating brew recipes (since `brew update-python-resources` depends on pipgrip)

We can work around this by excluding the offending versions ourselves in DVC, but ideally pipgrip would just drop versions where the wheel fails to build and continue testing other versions (if any are available)

**Comment by ddelange** [comment]
Hi 👋 

I understand that adding `aliyun-python-sdk-core-v3!=2.13.31` to dvc requirements is not ideal, although it might have to be the ultimate fallback in this case.

Was there a request to [yank](https://peps.python.org/pep-0592/) `aliyun-python-sdk-core-v3==2.13.31`? This indeed would be the preferred fix in this case. If they refuse/ignore, the next fallback would be for `oss2` to exclude the bad version in their requirements.

I looked a bit at how pip handles this bad version:
```console
$ pip install -vvv aliyun-python-sdk-core-v3==2.13.31
...
ERROR: Could not find a version that satisfies the requirement aliyun-python-sdk-core-v3==2.13.31 (from versions: 2.3.2, 2.3.3, 2.3.4, 2.3.5, 2.3.6, 2.3.7, 2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.4.4, 2.5.0, 2.5.1, 2.5.2, 2.5.3, 2.5.4, 2.5.5, 2.7.2, 2.8.2, 2.8.3, 2.8.4, 2.8.5, 2.8.6, 2.8.7, 2.8.8, 2.8.9, 2.9.0, 2.9.1, 2.9.3, 2.9.4, 2.10.1, 2.11.0, 2.11.1, 2.11.4, 2.11.5, 2.12.1, 2.13.0, 2.13.3, 2.13.8, 2.13.9, 2.13.10, 2.13.11, 2.13.31, 2.13.32, 2.13.33)
ERROR: No matching distribution found for aliyun-python-sdk-core-v3==2.13.31

$ pip install -vvv 'jmespath>=1' aliyun-python-sdk-core-v3
...
Removed aliyun-python-sdk-core-v3 from https://files.pythonhosted.org/packages/6a/3b/e7cebab62df2053fc3a034ef4c57b0732210d2865cfc8b885b25c2d1a5bf/aliyun-python-sdk-core-v3-2.13.3.tar.gz#sha256=04084a24f8639c0b3f7aceb4bd11a18f2bb67fb25ad81b62c0fd87f4b82f48ff from build tracker '/private/var/folders/_b/ldf_nfdx3qndz_5lvxxkchsc0000gn/T/pip-req-tracker-a93gjur3'
...
```

It looks like pip just emits a warning, removes the bad version from the set of available versions for this package, and continues.

I don't think this can be replicated in pipgrip. Due to the lazy loading nature, at the point when building this wheel fails, mixology has already selected this version as a candidate out of the available versions. Even if the exception would be caught, and this version 'yanked' from the available versions, I think it is not trivial to tell mixology 'oops, this version is not an available version after all', at least not at that point in the code.

**Comment by pmrowla** [comment]
> Was there a request to [yank](https://peps.python.org/pep-0592/) aliyun-python-sdk-core-v3==2.13.31? This indeed would be the preferred fix in this case. If they refuse/ignore, the next fallback would be for oss2 to exclude the bad version in their requirements.

We haven't made the request yet but I'm not sure whether or not anyone else has. I was also surprised that the package was still on pypi given that aliyun presumably knows about the issue since they fixed it in subsequent releases. (I'm also not sure that getting it excluded in `oss2` will work either given that it's also maintained by aliyun)

I mentioned this in the other issue, but being able to pass additional requirements into pipgrip via an env var would be an acceptable workaround for us.
