### ISSUE TITLE
Error when multiple extras are requested separately

### ISSUE THREAD

**Issue by ddelange** [ddelange/pipgrip#96]
I think there's also another related issue:

* `pipgrip -vv --tree ray[tune]` → Successful
* `pipgrip -vv --tree ray[rllib]` → Successful
* `pipgrip -vv --tree ray[tune,rllib]` → Successful
* `pipgrip -vv --tree ray[tune] ray[rllib]` → Fails

<details><summary>Command output</summary><p>

```console
Traceback (most recent call last):
  File "/home/vagrant/.local/bin/pipgrip", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/vagrant/.local/lib/python3.8/site-packages/pipgrip/cli.py", line 460, in main
    raise RuntimeError(
RuntimeError: Unexpected partial solution encountered, not all packages have decisions

```

</p></details>

_Originally posted by @jdchn in https://github.com/ddelange/pipgrip/issues/95#issuecomment-1221907175_

**Comment by ddelange** [comment]
[this](https://github.com/ddelange/pipgrip/blob/cd1302494b8be9b5edb698773aa365dd18b66399/src/pipgrip/libs/mixology/term.py#L147) set union handles it in most cases, but somehow we never reach the call of this `Term.intersect` in the example above.

**Comment by ddelange** [comment]
When this pattern occurs a level deeper (so not two root dependencies like above), the set union hits and the lockfile will be correct, but the tree output is incorrect:
```
$ pipgrip --tree -vv pypicloud[azure-blob]==1.3.9
...
INFO: fact: pypicloud[azure-blob] (1.3.9) depends on smart-open[azure] (>=6.1.0)
INFO: fact: pypicloud[azure-blob] (1.3.9) depends on smart-open[s3,http] (*)
...
INFO: discovering smart-open[azure,http,s3]
...
pypicloud[azure-blob]==1.3.9 (1.3.9)
├── smart-open[azure]>=6.1.0 (6.1.0)
│   ├── azure-common (1.1.28)
│   ├── boto3 (1.24.66)         # :(
├── smart-open[http,s3] (6.1.0)
│   ├── azure-common (1.1.28)   # :(
│   ├── boto3 (1.24.66)
```

**Comment by ddelange** [comment]
Temporarily adding `smart-open[azure]` and `smart-open[http,s3]` to pipgrip's requirements and running `pipgrip -vvv --tree .` also hits `RuntimeError: Unexpected partial solution encountered, not all packages have decisions`, most likely same error yet one level deeper. So this bug is most likely not related to `root_dep` related logic.
